### ISSUE TITLE
ACVP-AES-XTS occasionally provides out of range sequence numbers

### ISSUE THREAD

**Issue by v-roackerman** [usnistgov/ACVP-Server#354]
**environment**
Demo

**testSessionId**
535961

**vsId**
2509629

**Algorithm registration**
      {
        "algorithm": "ACVP-AES-XTS",
        "revision": "2.0",
        "direction": [
          "encrypt",
          "decrypt"
        ],
        "keyLen": [
          128,
          256
        ],
        "payloadLen": [
          512,
          4096,
          65536
        ],
        "tweakMode": [
          "number"
        ],
        "dataUnitLenMatchesPayload": true
      }

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/[endpoint] GET
Unsure what you mean.

**Expected behavior**
A sequence number in a range between 0 and 255 be provided.

**Additional context**
ACVP-AES-XTS ACVP documentation dictates that when the tweakMode field is set to “number”, the sequence number shall be between 0 and 255.
We sometimes get 256 from the NIST demo server forcing our code to exit.

https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-test-groups

**Comment by jbrock24** [comment]
I found the issue and have fixed it. It will go out with the next version. We'll post here when it's available on demo. Thanks for reporting the issue!

**Comment by livebe01** [comment]
Hi @v-roackerman, we just deployed the fix for this issue to Demo as part of the [v1.1.0.36](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.36) release. Are you be able to test it to confirm? Thank you.

**Comment by v-roackerman** [comment]
It is rare that I see it.  In fact, after the first time, it was two more months before I saw it again to provide this treport.
I will run it regardless as part of my job and report if not fixed.

**Comment by livebe01** [comment]
Okay. It was a very straightforward fix. Changing a 256 to a 255.

Ben



On Oct 7, 2024, at 1:10 PM, v-roackerman ***@***.***> wrote:



It is rare that I see it. In fact, after the first time, it was two more months before I saw it again to provide this treport.
I will run it regardless as part of my job and report if not fixed.

**Comment by livebe01** [comment]
The fix for this issue has been deployed to ACVTS Prod as part of the [v1.1.0.36](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.36) release.
